# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'inventory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage'

  target 'inventoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'inventoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
